{% set version = "1.0.1" %}

package:
  name: bunch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bunch/bunch-{{ version }}.tar.gz
  sha256: 50c77a0fc0cb372dfe48b5e11937d5f70e743adbf42683f3a6d2857645a76aaa

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - bunch

about:
  home: http://github.com/dsc/bunch
  license: MIT
  license_file: LICENSE.txt
  summary: 'A dot-accessible dictionary (a la JavaScript objects)'

extra:
  recipe-maintainers:
    - ocefpaf
