travis:
  secure:
    BINSTAR_TOKEN: JrX/XfSaY73pBk00ngBbIkgskojINYziX6XR6n/svHkxmKQuGE02PeNmrbUjjMRZ1MUh4BBwqZYgNJjPyHnUZznRwp5FR5E+z+FgU8VedcUPESrXqaQdq365bBfNwXXKN+H7dfVxCqOm+6dqTWlC989swz76wcF2Mm/d2P5jVEXYszTcWNzAd4XUA+k80H4mgPL9IvObZ5h9GLFMwXfY5Rcw7ifxFp7kgNA+BGgKh83+5YnkA7zyM9Fth0cG5cd3+KHtWXWsevkhlnu+zDIe4GZwf9Ty8JcLQ5b7U8u53msUlmO1cgbYPT6CLCaFJxOfwts2lrIINbvURRVTUkgQ6RXuPUrs1VnOImBQDZyx4Hybis4CUNFWXjrgqCWYw9a3mQMZhQ5rA+UHxW2nOgRGOXp+8VHL5/SzrW233Gl1f9Y8x94AfsV152D6c+Lv8pbBw4bmZSHUWMKgrxAey3Fgk5rTzW1iPeZerGPOFD6b2hF1gtAlgmzZ6me4vWYfUDIFLDmXcvz1iS4Qjk0WMb7HqTcMkiR3k3zu630cQxjBN/0ovJ4z6HRO6b9ttvTmgc6OgQZmfodxm9xam6SoOye15J55CqkL+mH8JyFsGKEcTF5yy+up+S8WSyPphQk3/Sj5EoPDdRHhfuaT7pRx4ifnjHFz8Ap/PDovwbQ2C7eUbFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
