travis:
  secure:
    BINSTAR_TOKEN: e6gYrAIt1ME6U/GEpqXfCq+g4Nf9Jd7N0iL5QAeyA+zL3sB/wPubvCkP3l3fCwLlh9y4YmvjImclLWDvy+hJg8FJQ4ODHs2RqL+iJUTYAQGKaBI9LlT9YrpULbaKtCrt8vP1G/y+qHwxC63WgF73ikTkbOChJ6vjYgcaPu4JzIyBQGHFjL9VN/jMH87MI3nTyIkrn0rstfbp/FiL7/DMLHmcsNInt1TOnigBaxyBMDFlk1GBFEZbRdPa0P8ozN64JnhhQgrEexpa3b2ouAFdybm5tJ4qZljcHeNPYN0nBVBBH4+pEaIH0fA0dHWmdVXL4qTnKPVqutH0aE2rl03sKdJJvK8Sa+5wl3KNedjy+jPHHglycwn7pxQW6koTbq0uL0jIvV/vX7hquDj9VTjPfVqCKNCfM2ylwcmCDgGVmMoSJ84ZPDwXEnuc7i7Jk8oyKz86JvuW5/Pipp3HmmT3bx/nJi/x4FSQcdaxhY0qNY6KRISrzkby3NDMGGGSfcnQn9cyKYLw6HrPvp7gYYY0972PF2W6ah/6TuuDt8aGyt2JDnow3tN+YA5z4HgRC4FWVF9FIxlwBcFHT7fad12+mG1RdlSLQA4M8mS7qq8evAhT04UIwbpV2+kwvDNX57HE7Y0M4qEPKCblE2MoEUYXwbXLFxhNo87AQxd8CzIbqoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
